variables:
  ELASTIC_PASSWORD: "$ELASTICSEARCH_PASSWORD"
  ELASTICSEARCH_PASSWORD: "$ELASTICSEARCH_PASSWORD"
  NOODLE_PASSWORD: "$NOODLE_PASSWORD"
  ES_HOST: "es01"

image: ruby:2.7
services:
  - name: elastic/elasticsearch:8.1.1
    alias: es01

stages:
  - run-tests

run-tests:
  stage: run-tests
  script:
    - sleep 60 # Wait for ES, wait for it, better later.
    - bin/elasticsearch-create-noodle-role.sh
    - bin/elasticsearch-create-noodle-user.sh
    - echo "${NOODLE_PASSWORD}" > config/.pw
    - gem update bundler
    - bundle config set path 'vendor/bundle'
    - bundle install
    - bundle exec rake test_authttps
