include:
  - template: Security/SAST.gitlab-ci.yml

default:
  image: ruby:2.7

stages:
  - run-tests
  - test

run-tests:
  stage: run-tests
  script:
    - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.15.2-amd64.deb
    - dpkg -i --force-confnew                                      elasticsearch-7.15.2-amd64.deb
    - service elasticsearch restart
    - sleep 5 # Wait for Elasticsearch to start :)
    - gem update bundler
    - bundle config set path 'vendor/bundle'
    - bundle install
    - bundle exec rake test
