development:
  elasticsearch_logging: true
  apm: true
  ecs_logging: true
  ecs_log_correlation: true

test:
  elasticsearch_logging: true

production:
  elasticsearch_logging: false
  apm: true
  ecs_logging: true
  ecs_log_correlation: true
