source 'https://rubygems.org'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'puma'
gem 'elasticsearch-persistence'
gem 'oj'
gem 'multi_json'
gem 'minitest'
gem 'minitest-reporters'
gem 'rack-test'
gem 'rake'
gem 'rspec'
gem 'rspec_rake'
gem 'hashie'
gem 'optimist'
gem 'pry', require: false
gem 'rest-client'
gem 'deepsort'
gem 'elastic-apm'
gem 'ecs-logging'
gem 'rackup'
gem 'codecov', require: false, group: :test
gem 'simplecov', require: false, group: :test_authttps_localhost
