source 'https://rubygems.org'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'thin'
gem 'elasticsearch-persistence', :git => 'https://github.com/elastic/elasticsearch-rails.git'
gem 'oj'
gem 'multi_json'
gem 'minitest'
gem 'minitest-reporters'
gem 'rake'
gem 'rspec'
gem 'rspec_rake'
gem 'hashie'
gem 'coveralls', require: false
gem 'trollop'
gem 'pry', require: false
gem 'rest-client'
