source 'https://rubygems.org'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'thin'
gem 'elasticsearch-persistence'
gem 'oj'
gem 'multi_json'
gem 'minitest'
gem 'minitest-reporters'
gem 'rake'
gem 'rspec'
gem 'hashie'
gem 'coveralls', require: false
gem 'trollop'
gem 'securerandom'