bin/noodlin create -i host -s neptune -p lms -P dev -f cpus=10 -f ramgigs=2 -f diskgigs=65536 -a role=web,elasticsearch acini.example.com
bin/noodlin create -i host -s mars -p financials -P preprod -f cpus=2 -f ramgigs=4 -f diskgigs=1024 -a role=web,ssh agnolotti.example.com
bin/noodlin create -i host -s neptune -p warehouse -P dev -f cpus=4 -f ramgigs=16 -f diskgigs=1024 -a role=web,puppetmaster alphabets.example.com
bin/noodlin create -i host -s moon -p lms -P preprod -f cpus=7 -f ramgigs=256 -f diskgigs=512 -a role=web,ssh anelli.example.com
bin/noodlin create -i host -s jupiter -p registration -P prod -f cpus=2 -f ramgigs=4 -f diskgigs=2048 -a role=web,puppetmaster anellini.example.com
bin/noodlin create -i host -s uranus -p financials -P preprod -f cpus=9 -f ramgigs=128 -f diskgigs=2 -a role=web,ssh bavette.example.com
bin/noodlin create -i host -s neptune -p hr -P preprod -f cpus=9 -f ramgigs=64 -f diskgigs=8192 -a role=app,git bigoli.example.com
bin/noodlin create -i host -s mars -p hr -P prod -f cpus=2 -f ramgigs=2 -f diskgigs=32 -a role=web,mariadb bucatini.example.com
bin/noodlin create -i host -s jupiter -p hr -P prod -f cpus=2 -f ramgigs=256 -f diskgigs=65536 -a role=app,ssh campanelle.example.com
bin/noodlin create -i host -s jupiter -p hr -P test -f cpus=8 -f ramgigs=8 -f diskgigs=2048 -a role=app,mariadb cannelloni.example.com
bin/noodlin create -i host -s jupiter -p warehouse -P prod -f cpus=7 -f ramgigs=64 -f diskgigs=32768 -a role=app,git capellini.example.com
bin/noodlin create -i host -s neptune -p lms -P prod -f cpus=9 -f ramgigs=128 -f diskgigs=32768 -a role=db,mariadb cappelletti.example.com
bin/noodlin create -i host -s mars -p hr -P test -f cpus=2 -f ramgigs=4 -f diskgigs=256 -a role=app,puppetmaster capunti.example.com
bin/noodlin create -i host -s neptune -p warehouse -P test -f cpus=5 -f ramgigs=64 -f diskgigs=2048 -a role=app,elasticsearch casarecce.example.com
bin/noodlin create -i host -s neptune -p warehouse -P dev -f cpus=6 -f ramgigs=128 -f diskgigs=2 -a role=db,git casoncelli.example.com
bin/noodlin create -i host -s neptune -p warehouse -P dev -f cpus=3 -f ramgigs=8 -f diskgigs=512 -a role=app,elasticsearch cavatappi.example.com
bin/noodlin create -i host -s neptune -p registration -P dev -f cpus=2 -f ramgigs=16 -f diskgigs=32768 -a role=app,git cavatelli.example.com
bin/noodlin create -i host -s moon -p lms -P prod -f cpus=7 -f ramgigs=4 -f diskgigs=4 -a role=app,mariadb cellentani.example.com
bin/noodlin create -i host -s jupiter -p financials -P test -f cpus=8 -f ramgigs=128 -f diskgigs=16384 -a role=web,elasticsearch cencioni.example.com
bin/noodlin create -i host -s neptune -p lms -P test -f cpus=4 -f ramgigs=2 -f diskgigs=8192 -a role=web,elasticsearch conchiglie.example.com
bin/noodlin create -i host -s mars -p hr -P prod -f cpus=1 -f ramgigs=128 -f diskgigs=16 -a role=db,elasticsearch conchigliette.example.com
bin/noodlin create -i host -s pluto -p hr -P test -f cpus=7 -f ramgigs=16 -f diskgigs=512 -a role=app,ssh conchiglioni.example.com
bin/noodlin create -i host -s neptune -p lms -P dev -f cpus=5 -f ramgigs=256 -f diskgigs=2 -a role=web,ssh corallini.example.com
bin/noodlin create -i host -s uranus -p lms -P preprod -f cpus=8 -f ramgigs=32 -f diskgigs=64 -a role=db,puppetmaster corzetti.example.com
bin/noodlin create -i host -s moon -p lms -P test -f cpus=7 -f ramgigs=2 -f diskgigs=64 -a role=db,git creste.example.com
bin/noodlin create -i host -s jupiter -p lms -P preprod -f cpus=6 -f ramgigs=128 -f diskgigs=128 -a role=db,puppetmaster croxetti.example.com
bin/noodlin create -i host -s mars -p warehouse -P dev -f cpus=10 -f ramgigs=8 -f diskgigs=64 -a role=db,git ditali.example.com
bin/noodlin create -i host -s mars -p hr -P dev -f cpus=3 -f ramgigs=2 -f diskgigs=64 -a role=app,ssh ditalini.example.com
bin/noodlin create -i host -s pluto -p financials -P prod -f cpus=2 -f ramgigs=2 -f diskgigs=512 -a role=app,mariadb egg.example.com
bin/noodlin create -i host -s uranus -p registration -P preprod -f cpus=10 -f ramgigs=256 -f diskgigs=65536 -a role=app,mariadb fagottini.example.com
bin/noodlin create -i host -s moon -p lms -P prod -f cpus=10 -f ramgigs=4 -f diskgigs=1024 -a role=app,ssh farfalle.example.com
bin/noodlin create -i host -s pluto -p financials -P prod -f cpus=7 -f ramgigs=2 -f diskgigs=256 -a role=web,puppetmaster farfalline.example.com
bin/noodlin create -i host -s jupiter -p hr -P preprod -f cpus=5 -f ramgigs=8 -f diskgigs=4096 -a role=app,puppetmaster farfalloni.example.com
bin/noodlin create -i host -s neptune -p warehouse -P test -f cpus=10 -f ramgigs=16 -f diskgigs=2 -a role=web,mariadb fettuccine.example.com
bin/noodlin create -i host -s pluto -p financials -P dev -f cpus=6 -f ramgigs=4 -f diskgigs=2 -a role=app,ssh fideos.example.com
bin/noodlin create -i host -s mars -p warehouse -P dev -f cpus=10 -f ramgigs=4 -f diskgigs=4 -a role=db,mariadb fideuà.example.com
bin/noodlin create -i host -s uranus -p financials -P test -f cpus=9 -f ramgigs=8 -f diskgigs=16384 -a role=db,puppetmaster filini.example.com
bin/noodlin create -i host -s moon -p hr -P dev -f cpus=10 -f ramgigs=16 -f diskgigs=64 -a role=db,puppetmaster fiorentine.example.com
bin/noodlin create -i host -s mars -p hr -P test -f cpus=10 -f ramgigs=128 -f diskgigs=8192 -a role=web,git fiori.example.com
bin/noodlin create -i host -s uranus -p warehouse -P preprod -f cpus=10 -f ramgigs=2 -f diskgigs=1024 -a role=app,puppetmaster foglie.example.com
bin/noodlin create -i host -s pluto -p financials -P dev -f cpus=10 -f ramgigs=32 -f diskgigs=32 -a role=web,git fregula.example.com
bin/noodlin create -i host -s mars -p lms -P dev -f cpus=9 -f ramgigs=64 -f diskgigs=32768 -a role=db,mariadb funghini.example.com
bin/noodlin create -i host -s jupiter -p registration -P dev -f cpus=5 -f ramgigs=2 -f diskgigs=256 -a role=web,ssh fusilli.example.com
bin/noodlin create -i host -s pluto -p hr -P preprod -f cpus=7 -f ramgigs=8 -f diskgigs=8192 -a role=app,mariadb garganelli.example.com
bin/noodlin create -i host -s uranus -p hr -P test -f cpus=10 -f ramgigs=128 -f diskgigs=2 -a role=web,ssh gemelli.example.com
bin/noodlin create -i host -s jupiter -p financials -P preprod -f cpus=9 -f ramgigs=4 -f diskgigs=512 -a role=db,git gigli.example.com
bin/noodlin create -i host -s neptune -p warehouse -P test -f cpus=1 -f ramgigs=8 -f diskgigs=2 -a role=app,mariadb gnocchi.example.com
bin/noodlin create -i host -s neptune -p registration -P dev -f cpus=9 -f ramgigs=2 -f diskgigs=65536 -a role=app,elasticsearch gramigna.example.com
bin/noodlin create -i host -s uranus -p warehouse -P preprod -f cpus=4 -f ramgigs=256 -f diskgigs=64 -a role=web,ssh grattini.example.com
bin/noodlin create -i host -s moon -p registration -P preprod -f cpus=10 -f ramgigs=8 -f diskgigs=1024 -a role=web,mariadb grattoni.example.com
bin/noodlin create -i host -s moon -p hr -P test -f cpus=3 -f ramgigs=128 -f diskgigs=32 -a role=web,git lanterne.example.com
bin/noodlin create -i host -s neptune -p hr -P test -f cpus=8 -f ramgigs=2 -f diskgigs=128 -a role=app,mariadb lasagne.example.com
bin/noodlin create -i host -s jupiter -p registration -P test -f cpus=7 -f ramgigs=256 -f diskgigs=256 -a role=db,mariadb lasagnette.example.com
bin/noodlin create -i host -s neptune -p lms -P test -f cpus=10 -f ramgigs=2 -f diskgigs=1024 -a role=db,ssh linguine.example.com
bin/noodlin create -i host -s uranus -p warehouse -P dev -f cpus=8 -f ramgigs=64 -f diskgigs=8 -a role=app,ssh lumache.example.com
bin/noodlin create -i host -s pluto -p registration -P preprod -f cpus=6 -f ramgigs=128 -f diskgigs=8 -a role=app,git lumaconi.example.com
bin/noodlin create -i host -s mars -p lms -P dev -f cpus=1 -f ramgigs=4 -f diskgigs=65536 -a role=app,puppetmaster macaroni.example.com
bin/noodlin create -i host -s uranus -p financials -P preprod -f cpus=7 -f ramgigs=16 -f diskgigs=128 -a role=app,git mafaldine.example.com
bin/noodlin create -i host -s pluto -p registration -P test -f cpus=1 -f ramgigs=4 -f diskgigs=1024 -a role=web,elasticsearch maltagliati.example.com
bin/noodlin create -i host -s mars -p financials -P preprod -f cpus=5 -f ramgigs=2 -f diskgigs=4096 -a role=web,elasticsearch mandala.example.com
bin/noodlin create -i host -s moon -p financials -P dev -f cpus=10 -f ramgigs=2 -f diskgigs=65536 -a role=db,ssh manicotti.example.com
bin/noodlin create -i host -s neptune -p hr -P dev -f cpus=2 -f ramgigs=16 -f diskgigs=8 -a role=web,mariadb marille.example.com
bin/noodlin create -i host -s moon -p warehouse -P test -f cpus=3 -f ramgigs=256 -f diskgigs=32 -a role=db,elasticsearch maultasche.example.com
bin/noodlin create -i host -s mars -p financials -P preprod -f cpus=3 -f ramgigs=8 -f diskgigs=64 -a role=app,puppetmaster midolline.example.com
bin/noodlin create -i host -s jupiter -p financials -P test -f cpus=6 -f ramgigs=16 -f diskgigs=4 -a role=web,git mostaccioli.example.com
bin/noodlin create -i host -s moon -p registration -P prod -f cpus=3 -f ramgigs=8 -f diskgigs=2 -a role=web,puppetmaster occhi.example.com
bin/noodlin create -i host -s pluto -p financials -P prod -f cpus=1 -f ramgigs=64 -f diskgigs=2 -a role=db,elasticsearch orecchiette.example.com
bin/noodlin create -i host -s moon -p lms -P test -f cpus=8 -f ramgigs=128 -f diskgigs=256 -a role=web,mariadb orzo.example.com
bin/noodlin create -i host -s jupiter -p financials -P prod -f cpus=2 -f ramgigs=4 -f diskgigs=32768 -a role=app,ssh paccheri.example.com
bin/noodlin create -i host -s mars -p registration -P prod -f cpus=6 -f ramgigs=4 -f diskgigs=8192 -a role=app,ssh pappardelle.example.com
bin/noodlin create -i host -s pluto -p financials -P dev -f cpus=10 -f ramgigs=4 -f diskgigs=512 -a role=web,mariadb passatelli.example.com
bin/noodlin create -i host -s moon -p warehouse -P test -f cpus=7 -f ramgigs=8 -f diskgigs=4096 -a role=app,git pastina.example.com
bin/noodlin create -i host -s neptune -p lms -P test -f cpus=8 -f ramgigs=8 -f diskgigs=65536 -a role=app,puppetmaster pearl.example.com
bin/noodlin create -i host -s neptune -p registration -P preprod -f cpus=1 -f ramgigs=8 -f diskgigs=512 -a role=app,ssh pelmeni.example.com
bin/noodlin create -i host -s moon -p warehouse -P dev -f cpus=6 -f ramgigs=64 -f diskgigs=16 -a role=web,ssh penne.example.com
bin/noodlin create -i host -s mars -p financials -P test -f cpus=5 -f ramgigs=256 -f diskgigs=32 -a role=app,ssh perciatelli.example.com
bin/noodlin create -i host -s uranus -p registration -P dev -f cpus=7 -f ramgigs=32 -f diskgigs=8192 -a role=web,git pici.example.com
bin/noodlin create -i host -s uranus -p warehouse -P dev -f cpus=3 -f ramgigs=16 -f diskgigs=32768 -a role=web,git pierogi.example.com
bin/noodlin create -i host -s uranus -p lms -P test -f cpus=6 -f ramgigs=4 -f diskgigs=32768 -a role=app,mariadb pipe.example.com
bin/noodlin create -i host -s uranus -p lms -P test -f cpus=8 -f ramgigs=256 -f diskgigs=16384 -a role=app,mariadb pizzoccheri.example.com
bin/noodlin create -i host -s pluto -p financials -P prod -f cpus=5 -f ramgigs=2 -f diskgigs=256 -a role=app,ssh puntine.example.com
bin/noodlin create -i host -s moon -p financials -P preprod -f cpus=1 -f ramgigs=2 -f diskgigs=1024 -a role=app,git quadrefiore.example.com
bin/noodlin create -i host -s mars -p warehouse -P dev -f cpus=3 -f ramgigs=4 -f diskgigs=64 -a role=db,elasticsearch quadrettini.example.com
bin/noodlin create -i host -s jupiter -p warehouse -P test -f cpus=9 -f ramgigs=8 -f diskgigs=4096 -a role=web,ssh radiatori.example.com
bin/noodlin create -i host -s mars -p warehouse -P preprod -f cpus=3 -f ramgigs=32 -f diskgigs=16 -a role=web,git ravioli.example.com
bin/noodlin create -i host -s uranus -p warehouse -P prod -f cpus=7 -f ramgigs=8 -f diskgigs=4096 -a role=web,mariadb ricciolini.example.com
bin/noodlin create -i host -s neptune -p financials -P preprod -f cpus=10 -f ramgigs=32 -f diskgigs=4096 -a role=web,mariadb ricciutelle.example.com
bin/noodlin create -i host -s mars -p lms -P preprod -f cpus=10 -f ramgigs=8 -f diskgigs=64 -a role=db,git rigatoni.example.com
bin/noodlin create -i host -s jupiter -p lms -P preprod -f cpus=3 -f ramgigs=2 -f diskgigs=1024 -a role=app,elasticsearch risi.example.com
bin/noodlin create -i host -s moon -p lms -P dev -f cpus=10 -f ramgigs=128 -f diskgigs=64 -a role=app,ssh rotelle.example.com
bin/noodlin create -i host -s pluto -p financials -P preprod -f cpus=7 -f ramgigs=128 -f diskgigs=8192 -a role=db,puppetmaster rotini.example.com
bin/noodlin create -i host -s neptune -p hr -P dev -f cpus=1 -f ramgigs=128 -f diskgigs=512 -a role=app,puppetmaster sagne.example.com
bin/noodlin create -i host -s moon -p hr -P preprod -f cpus=9 -f ramgigs=32 -f diskgigs=512 -a role=db,git seme.example.com
bin/noodlin create -i host -s neptune -p financials -P test -f cpus=6 -f ramgigs=32 -f diskgigs=32 -a role=web,elasticsearch sorprese.example.com
bin/noodlin create -i host -s neptune -p registration -P test -f cpus=2 -f ramgigs=32 -f diskgigs=64 -a role=db,elasticsearch spaghetti.example.com
bin/noodlin create -i host -s neptune -p financials -P preprod -f cpus=3 -f ramgigs=128 -f diskgigs=65536 -a role=web,mariadb spaghettini.example.com
bin/noodlin create -i host -s pluto -p warehouse -P test -f cpus=1 -f ramgigs=4 -f diskgigs=8192 -a role=app,ssh spaghettoni.example.com
bin/noodlin create -i host -s jupiter -p lms -P preprod -f cpus=9 -f ramgigs=4 -f diskgigs=32768 -a role=web,ssh spätzle.example.com
bin/noodlin create -i host -s mars -p financials -P dev -f cpus=8 -f ramgigs=128 -f diskgigs=64 -a role=app,ssh stelle.example.com
bin/noodlin create -i host -s mars -p lms -P prod -f cpus=8 -f ramgigs=128 -f diskgigs=2048 -a role=app,puppetmaster stelline.example.com
bin/noodlin create -i host -s moon -p lms -P dev -f cpus=1 -f ramgigs=4 -f diskgigs=16384 -a role=app,mariadb stortini.example.com
bin/noodlin create -i host -s pluto -p warehouse -P preprod -f cpus=8 -f ramgigs=4 -f diskgigs=1024 -a role=db,elasticsearch stringozzi.example.com
bin/noodlin create -i host -s pluto -p lms -P prod -f cpus=4 -f ramgigs=2 -f diskgigs=64 -a role=app,ssh strozzapreti.example.com
bin/noodlin create -i host -s mars -p warehouse -P dev -f cpus=3 -f ramgigs=16 -f diskgigs=4096 -a role=web,puppetmaster tagliatelle.example.com
bin/noodlin create -i host -s neptune -p lms -P dev -f cpus=1 -f ramgigs=4 -f diskgigs=1024 -a role=web,mariadb torchio.example.com
bin/noodlin create -i host -s uranus -p financials -P preprod -f cpus=5 -f ramgigs=8 -f diskgigs=256 -a role=app,ssh tortellini.example.com
bin/noodlin create -i host -s uranus -p financials -P preprod -f cpus=6 -f ramgigs=64 -f diskgigs=128 -a role=app,elasticsearch tortelloni.example.com
bin/noodlin create -i host -s mars -p hr -P preprod -f cpus=9 -f ramgigs=16 -f diskgigs=32768 -a role=app,puppetmaster tortiglioni.example.com
bin/noodlin create -i host -s moon -p lms -P prod -f cpus=4 -f ramgigs=2 -f diskgigs=32768 -a role=web,mariadb trenette.example.com
bin/noodlin create -i host -s mars -p warehouse -P preprod -f cpus=1 -f ramgigs=4 -f diskgigs=2048 -a role=db,elasticsearch tripolini.example.com
bin/noodlin create -i host -s neptune -p lms -P preprod -f cpus=10 -f ramgigs=128 -f diskgigs=32 -a role=web,puppetmaster trofie.example.com
bin/noodlin create -i host -s neptune -p hr -P test -f cpus=2 -f ramgigs=16 -f diskgigs=32 -a role=web,git ziti.example.com
