#!/usr/bin/ruby

require_relative '../lib/noodle'
require 'pry'

puts "For example:"
puts "Noodle::Node.search( query: { match: { name: 'cheese1.example.com'}})"
puts
puts "Or:"
puts "r = Noodle::Node.search( query: { match: { 'params.site' => 'moon'} } )"
puts
puts "Or:"
puts "r = Noodle::Node.search( query: { match: { 'params.site' => 'moon'} } ).response.hits.hits.collect{|hit| hit._source.name}"
puts
puts "Or this which means OR:"
puts "r = Noodle::Node.search( query: { bool: { must: ["
puts "                                            { match: { 'params.project' => 'luun'}},"
puts "                                            { match: { site: 'moon'}}"
puts "                                        ]}}).response.hits.hits.collect{|hit| hit._source.name}"
puts
puts "r = Noodle::Node.search( query: { multi_match: { query: 'luun', fields: "
puts "                      ['params.project','facts.project']}}).response.hits.hits.collect{|hit| hit._source.name}"
puts

r = Noodle::Node.search( query: { match: { 'params.site' => 'moon'} } )

pry

